### ISSUE TITLE
runbook project generator fails graceless on invalid gem names

### ISSUE THREAD

**Issue by fwolfst** [braintree/runbook#12]
When providing a project name that cannot be used as gem name (e.g. starting with numbers), the project generator will print an error but continue to request user input, until it finally fails
```
runbook generate project 7l
         run  bundle gem 7l --test rspec --no-coc --no-mit from "."
Creating gem '7l'...
Invalid gem name 7l Please give a name which does not start with numbers.
      remove  7l/7l.gemspec
      remove  7l/README.md
      remove  7l/Gemfile
      remove  7l/lib/7l.rb
      remove  7l/lib/7l/version.rb
Where should shared runbook code live?
Use `lib/7l` for runbook-only projects
Use `lib/7l/runbook` for projects used for non-runbook tasks
Shared runbook code path: lib/7l/runbook
      create  7l/README.md
      create  7l/Gemfile
      create  7l/lib/7l.rb
Traceback (most recent call last):
# ...
 1: from /home/void/.rvm/gems/ruby-2.6.1/gems/thor-0.20.3/lib/thor/actions/file_manipulation.rb:272:in `gsub_file'
/home/void/rvm/gems/ruby-2.6.1/gems/thor-0.20.3/lib/thor/actions/file_manipulation.rb:272:in `binread': No such file or directory @ rb_sysopen - /home/void/projects/7l/other/tasks/7l/Rakefile (Errno::ENOENT)
```

User experience would be improved, if the program fails (statuscode != 0) directly when gem creation fails.

**Comment by pblesi** [comment]
Thanks for the callout @fwolfst. 

I've added the following fixes:

* https://github.com/braintree/runbook/commit/51cc40ccb3b54a7d17ebf70fe8e36c2606df266c
* https://github.com/braintree/runbook/commit/bf2da91734280bba8b1ab53f345915eb0dd09186

These changes will be included in the next release.
