### ISSUE TITLE
Asserting if something is installed

### ISSUE THREAD

**Issue by Zejnilovic** [braintree/runbook#2]
Hello, I am currently testing out this app of yours and came to a halt with the use case bellow

**Usecase**: Check if something is installed. If not install, otherwise print a message. Basically, I need to check if there is an executable for something, that means using `which executable_name`

**Problem**: `which` returns non zero exit which then throws a huge error in my face. This is also true for `command`, `type`, `hash`.

Is there a way to handle this or do I need to use try/catch?

The error: 
```bash
Traceback (most recent call last):
	20: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sshkit-1.16.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	19: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sshkit-1.16.0/lib/sshkit/backends/abstract.rb:29:in `run'
	18: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sshkit-1.16.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
	17: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/runbook-0.13.0/lib/runbook/helpers/ssh_kit_helper.rb:90:in `block (2 levels) in with_ssh_config'
	16: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/runbook-0.13.0/lib/runbook/helpers/ssh_kit_helper.rb:90:in `instance_exec'
	15: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/runbook-0.13.0/lib/runbook/helpers/ssh_kit_helper.rb:121:in `block in _with_block'
	14: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/runbook-0.13.0/lib/runbook/helpers/ssh_kit_helper.rb:121:in `instance_exec'
	13: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/runbook-0.13.0/lib/runbook/helpers/ssh_kit_helper.rb:129:in `block in _within_block'
	12: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/runbook-0.13.0/lib/runbook/helpers/ssh_kit_helper.rb:129:in `instance_exec'
	11: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/runbook-0.13.0/lib/runbook/helpers/ssh_kit_helper.rb:113:in `block in _as_block'
	10: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/runbook-0.13.0/lib/runbook/helpers/ssh_kit_helper.rb:113:in `instance_exec'
	 9: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/runbook-0.13.0/lib/runbook/runs/ssh_kit.rb:75:in `block (2 levels) in runbook__statements__capture'
	 8: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sshkit-1.16.0/lib/sshkit/backends/abstract.rb:60:in `capture'
	 7: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sshkit-1.16.0/lib/sshkit/backends/abstract.rb:141:in `create_command_and_execute'
	 6: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sshkit-1.16.0/lib/sshkit/backends/abstract.rb:141:in `tap'
	 5: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sshkit-1.16.0/lib/sshkit/backends/abstract.rb:141:in `block in create_command_and_execute'
	 4: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sshkit-1.16.0/lib/sshkit/backends/local.rb:46:in `execute_command'
	 3: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/2.6.0/open3.rb:101:in `popen3'
	 2: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/2.6.0/open3.rb:219:in `popen_run'
	 1: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sshkit-1.16.0/lib/sshkit/backends/local.rb:64:in `block in execute_command'
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sshkit-1.16.0/lib/sshkit/command.rb:99:in `exit_status=': which exit status: 256 (SSHKit::Command::Failed)
which stdout: Nothing written
which stderr: Nothing written
1: from /Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sshkit-1.16.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sshkit-1.16.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as user@localhost: which exit status: 256 (SSHKit::Runner::ExecuteError)
which stdout: Nothing written
which stderr: Nothing written
```

**Comment by pblesi** [comment]
You can add `|| true` to the end of your command. The command will always have a response code of `0` regardless of the response code of the first command. So `which does_not_exist || true` will never raise a `SSHKit::Command::Failed` exception and will output the path to a command if it exists. [Capturing this value](https://github.com/braintree/runbook#capture) will thus allow you to determine if something is installed.

**Comment by Zejnilovic** [comment]
I don't want to reopen this if it is just my own brain fart again but please look at the lines bellow:

```ruby
capture "which zsh || true", into: :zsh
notice @zsh
capture "which zsh", into: :alfa
notice @alfa
```

**Output**
```bash
Capturing output of `which zsh || true`

      11 /usr/local/bin/zsh
    ✔ 11 user@localhost 0.008s
Notice:
Capturing output of `which zsh`

      12 which zsh
      12 /usr/local/bin/zsh
    ✔ 12 user@localhost 0.005s
Notice:
```

Could/would you please assist?
I am not even sure if this is the correct way how to use the variables from `into`, but there is an example with the statement `ask` which does so.

**Comment by pblesi** [comment]
You will need to reference the `into` values within a `ruby_command` block. This is because first Runbook "compiles" all the statements and then executes them. At the time the arguments to `notice` are evaluated, the `capture` commands have not run yet. To get around this you lazy-evaluate the arguments to notice by putting them in a `ruby_command` block, so this example should work:

```
capture "which zsh || true", into: :zsh
ruby_command { notice @zsh }
capture "which zsh", into: :alfa
ruby_command { notice @alfa }
```
